// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: proto/file/v1/file.proto

package pbfile

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerUserId   uint64                 `protobuf:"varint,2,opt,name=owner_user_id,json=ownerUserId,proto3" json:"owner_user_id,omitempty"`
	BizType       string                 `protobuf:"bytes,3,opt,name=biz_type,json=bizType,proto3" json:"biz_type,omitempty"` // private/group
	PeerId        uint64                 `protobuf:"varint,4,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	GroupId       uint64                 `protobuf:"varint,5,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	ObjectKey     string                 `protobuf:"bytes,6,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	FileName      string                 `protobuf:"bytes,7,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileSize      int64                  `protobuf:"varint,8,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	MimeType      string                 `protobuf:"bytes,9,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Status        string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"` // pending_upload/uploaded/scanning/ok/rejected
	RejectReason  string                 `protobuf:"bytes,11,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"`
	UploadUrl     string                 `protobuf:"bytes,12,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`
	DownloadUrl   string                 `protobuf:"bytes,13,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileItem) Reset() {
	*x = FileItem{}
	mi := &file_proto_file_v1_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileItem) ProtoMessage() {}

func (x *FileItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_v1_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileItem.ProtoReflect.Descriptor instead.
func (*FileItem) Descriptor() ([]byte, []int) {
	return file_proto_file_v1_file_proto_rawDescGZIP(), []int{0}
}

func (x *FileItem) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FileItem) GetOwnerUserId() uint64 {
	if x != nil {
		return x.OwnerUserId
	}
	return 0
}

func (x *FileItem) GetBizType() string {
	if x != nil {
		return x.BizType
	}
	return ""
}

func (x *FileItem) GetPeerId() uint64 {
	if x != nil {
		return x.PeerId
	}
	return 0
}

func (x *FileItem) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *FileItem) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *FileItem) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *FileItem) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *FileItem) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *FileItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FileItem) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

func (x *FileItem) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *FileItem) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *FileItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *FileItem) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type PrepareUploadRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OwnerUserId    uint64                 `protobuf:"varint,1,opt,name=owner_user_id,json=ownerUserId,proto3" json:"owner_user_id,omitempty"`
	ClientUploadId string                 `protobuf:"bytes,2,opt,name=client_upload_id,json=clientUploadId,proto3" json:"client_upload_id,omitempty"`
	FileName       string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileSize       int64                  `protobuf:"varint,4,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	MimeType       string                 `protobuf:"bytes,5,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	BizType        string                 `protobuf:"bytes,6,opt,name=biz_type,json=bizType,proto3" json:"biz_type,omitempty"` // private/group
	PeerId         uint64                 `protobuf:"varint,7,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	GroupId        uint64                 `protobuf:"varint,8,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PrepareUploadRequest) Reset() {
	*x = PrepareUploadRequest{}
	mi := &file_proto_file_v1_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareUploadRequest) ProtoMessage() {}

func (x *PrepareUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_v1_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareUploadRequest.ProtoReflect.Descriptor instead.
func (*PrepareUploadRequest) Descriptor() ([]byte, []int) {
	return file_proto_file_v1_file_proto_rawDescGZIP(), []int{1}
}

func (x *PrepareUploadRequest) GetOwnerUserId() uint64 {
	if x != nil {
		return x.OwnerUserId
	}
	return 0
}

func (x *PrepareUploadRequest) GetClientUploadId() string {
	if x != nil {
		return x.ClientUploadId
	}
	return ""
}

func (x *PrepareUploadRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *PrepareUploadRequest) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *PrepareUploadRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *PrepareUploadRequest) GetBizType() string {
	if x != nil {
		return x.BizType
	}
	return ""
}

func (x *PrepareUploadRequest) GetPeerId() uint64 {
	if x != nil {
		return x.PeerId
	}
	return 0
}

func (x *PrepareUploadRequest) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type PrepareUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *FileItem              `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareUploadResponse) Reset() {
	*x = PrepareUploadResponse{}
	mi := &file_proto_file_v1_file_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareUploadResponse) ProtoMessage() {}

func (x *PrepareUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_v1_file_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareUploadResponse.ProtoReflect.Descriptor instead.
func (*PrepareUploadResponse) Descriptor() ([]byte, []int) {
	return file_proto_file_v1_file_proto_rawDescGZIP(), []int{2}
}

func (x *PrepareUploadResponse) GetFile() *FileItem {
	if x != nil {
		return x.File
	}
	return nil
}

type CommitUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        uint64                 `protobuf:"varint,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	OwnerUserId   uint64                 `protobuf:"varint,2,opt,name=owner_user_id,json=ownerUserId,proto3" json:"owner_user_id,omitempty"`
	Etag          string                 `protobuf:"bytes,3,opt,name=etag,proto3" json:"etag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitUploadRequest) Reset() {
	*x = CommitUploadRequest{}
	mi := &file_proto_file_v1_file_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitUploadRequest) ProtoMessage() {}

func (x *CommitUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_v1_file_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitUploadRequest.ProtoReflect.Descriptor instead.
func (*CommitUploadRequest) Descriptor() ([]byte, []int) {
	return file_proto_file_v1_file_proto_rawDescGZIP(), []int{3}
}

func (x *CommitUploadRequest) GetFileId() uint64 {
	if x != nil {
		return x.FileId
	}
	return 0
}

func (x *CommitUploadRequest) GetOwnerUserId() uint64 {
	if x != nil {
		return x.OwnerUserId
	}
	return 0
}

func (x *CommitUploadRequest) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

type CommitUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *FileItem              `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitUploadResponse) Reset() {
	*x = CommitUploadResponse{}
	mi := &file_proto_file_v1_file_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitUploadResponse) ProtoMessage() {}

func (x *CommitUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_v1_file_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitUploadResponse.ProtoReflect.Descriptor instead.
func (*CommitUploadResponse) Descriptor() ([]byte, []int) {
	return file_proto_file_v1_file_proto_rawDescGZIP(), []int{4}
}

func (x *CommitUploadResponse) GetFile() *FileItem {
	if x != nil {
		return x.File
	}
	return nil
}

type GetFileRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FileId         uint64                 `protobuf:"varint,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	OperatorUserId uint64                 `protobuf:"varint,2,opt,name=operator_user_id,json=operatorUserId,proto3" json:"operator_user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetFileRequest) Reset() {
	*x = GetFileRequest{}
	mi := &file_proto_file_v1_file_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileRequest) ProtoMessage() {}

func (x *GetFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_v1_file_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileRequest.ProtoReflect.Descriptor instead.
func (*GetFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_file_v1_file_proto_rawDescGZIP(), []int{5}
}

func (x *GetFileRequest) GetFileId() uint64 {
	if x != nil {
		return x.FileId
	}
	return 0
}

func (x *GetFileRequest) GetOperatorUserId() uint64 {
	if x != nil {
		return x.OperatorUserId
	}
	return 0
}

type GetFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *FileItem              `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileResponse) Reset() {
	*x = GetFileResponse{}
	mi := &file_proto_file_v1_file_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileResponse) ProtoMessage() {}

func (x *GetFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_v1_file_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileResponse.ProtoReflect.Descriptor instead.
func (*GetFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_file_v1_file_proto_rawDescGZIP(), []int{6}
}

func (x *GetFileResponse) GetFile() *FileItem {
	if x != nil {
		return x.File
	}
	return nil
}

type ApplyScanResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        uint64                 `protobuf:"varint,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Result        string                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"` // ok/rejected
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyScanResultRequest) Reset() {
	*x = ApplyScanResultRequest{}
	mi := &file_proto_file_v1_file_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyScanResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyScanResultRequest) ProtoMessage() {}

func (x *ApplyScanResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_v1_file_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyScanResultRequest.ProtoReflect.Descriptor instead.
func (*ApplyScanResultRequest) Descriptor() ([]byte, []int) {
	return file_proto_file_v1_file_proto_rawDescGZIP(), []int{7}
}

func (x *ApplyScanResultRequest) GetFileId() uint64 {
	if x != nil {
		return x.FileId
	}
	return 0
}

func (x *ApplyScanResultRequest) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ApplyScanResultRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ApplyScanResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *FileItem              `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyScanResultResponse) Reset() {
	*x = ApplyScanResultResponse{}
	mi := &file_proto_file_v1_file_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyScanResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyScanResultResponse) ProtoMessage() {}

func (x *ApplyScanResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_v1_file_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyScanResultResponse.ProtoReflect.Descriptor instead.
func (*ApplyScanResultResponse) Descriptor() ([]byte, []int) {
	return file_proto_file_v1_file_proto_rawDescGZIP(), []int{8}
}

func (x *ApplyScanResultResponse) GetFile() *FileItem {
	if x != nil {
		return x.File
	}
	return nil
}

var File_proto_file_v1_file_proto protoreflect.FileDescriptor

const file_proto_file_v1_file_proto_rawDesc = "" +
	"\n" +
	"\x18proto/file/v1/file.proto\x12\afile.v1\"\xc0\x03\n" +
	"\bFileItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\"\n" +
	"\rowner_user_id\x18\x02 \x01(\x04R\vownerUserId\x12\x19\n" +
	"\bbiz_type\x18\x03 \x01(\tR\abizType\x12\x17\n" +
	"\apeer_id\x18\x04 \x01(\x04R\x06peerId\x12\x19\n" +
	"\bgroup_id\x18\x05 \x01(\x04R\agroupId\x12\x1d\n" +
	"\n" +
	"object_key\x18\x06 \x01(\tR\tobjectKey\x12\x1b\n" +
	"\tfile_name\x18\a \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_size\x18\b \x01(\x03R\bfileSize\x12\x1b\n" +
	"\tmime_type\x18\t \x01(\tR\bmimeType\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12#\n" +
	"\rreject_reason\x18\v \x01(\tR\frejectReason\x12\x1d\n" +
	"\n" +
	"upload_url\x18\f \x01(\tR\tuploadUrl\x12!\n" +
	"\fdownload_url\x18\r \x01(\tR\vdownloadUrl\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0e \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\x03R\tupdatedAt\"\x8a\x02\n" +
	"\x14PrepareUploadRequest\x12\"\n" +
	"\rowner_user_id\x18\x01 \x01(\x04R\vownerUserId\x12(\n" +
	"\x10client_upload_id\x18\x02 \x01(\tR\x0eclientUploadId\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_size\x18\x04 \x01(\x03R\bfileSize\x12\x1b\n" +
	"\tmime_type\x18\x05 \x01(\tR\bmimeType\x12\x19\n" +
	"\bbiz_type\x18\x06 \x01(\tR\abizType\x12\x17\n" +
	"\apeer_id\x18\a \x01(\x04R\x06peerId\x12\x19\n" +
	"\bgroup_id\x18\b \x01(\x04R\agroupId\">\n" +
	"\x15PrepareUploadResponse\x12%\n" +
	"\x04file\x18\x01 \x01(\v2\x11.file.v1.FileItemR\x04file\"f\n" +
	"\x13CommitUploadRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\x04R\x06fileId\x12\"\n" +
	"\rowner_user_id\x18\x02 \x01(\x04R\vownerUserId\x12\x12\n" +
	"\x04etag\x18\x03 \x01(\tR\x04etag\"=\n" +
	"\x14CommitUploadResponse\x12%\n" +
	"\x04file\x18\x01 \x01(\v2\x11.file.v1.FileItemR\x04file\"S\n" +
	"\x0eGetFileRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\x04R\x06fileId\x12(\n" +
	"\x10operator_user_id\x18\x02 \x01(\x04R\x0eoperatorUserId\"8\n" +
	"\x0fGetFileResponse\x12%\n" +
	"\x04file\x18\x01 \x01(\v2\x11.file.v1.FileItemR\x04file\"a\n" +
	"\x16ApplyScanResultRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\x04R\x06fileId\x12\x16\n" +
	"\x06result\x18\x02 \x01(\tR\x06result\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"@\n" +
	"\x17ApplyScanResultResponse\x12%\n" +
	"\x04file\x18\x01 \x01(\v2\x11.file.v1.FileItemR\x04file2\xbe\x02\n" +
	"\vFileService\x12N\n" +
	"\rPrepareUpload\x12\x1d.file.v1.PrepareUploadRequest\x1a\x1e.file.v1.PrepareUploadResponse\x12K\n" +
	"\fCommitUpload\x12\x1c.file.v1.CommitUploadRequest\x1a\x1d.file.v1.CommitUploadResponse\x12<\n" +
	"\aGetFile\x12\x17.file.v1.GetFileRequest\x1a\x18.file.v1.GetFileResponse\x12T\n" +
	"\x0fApplyScanResult\x12\x1f.file.v1.ApplyScanResultRequest\x1a .file.v1.ApplyScanResultResponseB\x1dZ\x1bpim/internal/file/pb;pbfileb\x06proto3"

var (
	file_proto_file_v1_file_proto_rawDescOnce sync.Once
	file_proto_file_v1_file_proto_rawDescData []byte
)

func file_proto_file_v1_file_proto_rawDescGZIP() []byte {
	file_proto_file_v1_file_proto_rawDescOnce.Do(func() {
		file_proto_file_v1_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_file_v1_file_proto_rawDesc), len(file_proto_file_v1_file_proto_rawDesc)))
	})
	return file_proto_file_v1_file_proto_rawDescData
}

var file_proto_file_v1_file_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_file_v1_file_proto_goTypes = []any{
	(*FileItem)(nil),                // 0: file.v1.FileItem
	(*PrepareUploadRequest)(nil),    // 1: file.v1.PrepareUploadRequest
	(*PrepareUploadResponse)(nil),   // 2: file.v1.PrepareUploadResponse
	(*CommitUploadRequest)(nil),     // 3: file.v1.CommitUploadRequest
	(*CommitUploadResponse)(nil),    // 4: file.v1.CommitUploadResponse
	(*GetFileRequest)(nil),          // 5: file.v1.GetFileRequest
	(*GetFileResponse)(nil),         // 6: file.v1.GetFileResponse
	(*ApplyScanResultRequest)(nil),  // 7: file.v1.ApplyScanResultRequest
	(*ApplyScanResultResponse)(nil), // 8: file.v1.ApplyScanResultResponse
}
var file_proto_file_v1_file_proto_depIdxs = []int32{
	0, // 0: file.v1.PrepareUploadResponse.file:type_name -> file.v1.FileItem
	0, // 1: file.v1.CommitUploadResponse.file:type_name -> file.v1.FileItem
	0, // 2: file.v1.GetFileResponse.file:type_name -> file.v1.FileItem
	0, // 3: file.v1.ApplyScanResultResponse.file:type_name -> file.v1.FileItem
	1, // 4: file.v1.FileService.PrepareUpload:input_type -> file.v1.PrepareUploadRequest
	3, // 5: file.v1.FileService.CommitUpload:input_type -> file.v1.CommitUploadRequest
	5, // 6: file.v1.FileService.GetFile:input_type -> file.v1.GetFileRequest
	7, // 7: file.v1.FileService.ApplyScanResult:input_type -> file.v1.ApplyScanResultRequest
	2, // 8: file.v1.FileService.PrepareUpload:output_type -> file.v1.PrepareUploadResponse
	4, // 9: file.v1.FileService.CommitUpload:output_type -> file.v1.CommitUploadResponse
	6, // 10: file.v1.FileService.GetFile:output_type -> file.v1.GetFileResponse
	8, // 11: file.v1.FileService.ApplyScanResult:output_type -> file.v1.ApplyScanResultResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_file_v1_file_proto_init() }
func file_proto_file_v1_file_proto_init() {
	if File_proto_file_v1_file_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_file_v1_file_proto_rawDesc), len(file_proto_file_v1_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_file_v1_file_proto_goTypes,
		DependencyIndexes: file_proto_file_v1_file_proto_depIdxs,
		MessageInfos:      file_proto_file_v1_file_proto_msgTypes,
	}.Build()
	File_proto_file_v1_file_proto = out.File
	file_proto_file_v1_file_proto_goTypes = nil
	file_proto_file_v1_file_proto_depIdxs = nil
}
