// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: proto/group/v1/group.proto

package pbgroup

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// group 类型结构
type Group struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OwnerUserId   uint64                 `protobuf:"varint,3,opt,name=owner_user_id,json=ownerUserId,proto3" json:"owner_user_id,omitempty"`
	Notice        string                 `protobuf:"bytes,4,opt,name=notice,proto3" json:"notice,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Group) Reset() {
	*x = Group{}
	mi := &file_proto_group_v1_group_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_v1_group_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_proto_group_v1_group_proto_rawDescGZIP(), []int{0}
}

func (x *Group) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Group) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Group) GetOwnerUserId() uint64 {
	if x != nil {
		return x.OwnerUserId
	}
	return 0
}

func (x *Group) GetNotice() string {
	if x != nil {
		return x.Notice
	}
	return ""
}

func (x *Group) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Group) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// group 成员结构
type GroupMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupId       uint64                 `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	JoinedAt      int64                  `protobuf:"varint,5,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMember) Reset() {
	*x = GroupMember{}
	mi := &file_proto_group_v1_group_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMember) ProtoMessage() {}

func (x *GroupMember) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_v1_group_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMember.ProtoReflect.Descriptor instead.
func (*GroupMember) Descriptor() ([]byte, []int) {
	return file_proto_group_v1_group_proto_rawDescGZIP(), []int{1}
}

func (x *GroupMember) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GroupMember) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupMember) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GroupMember) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *GroupMember) GetJoinedAt() int64 {
	if x != nil {
		return x.JoinedAt
	}
	return 0
}

// 创建group请求
type CreateGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerUserId   uint64                 `protobuf:"varint,1,opt,name=owner_user_id,json=ownerUserId,proto3" json:"owner_user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	MemberUserIds []uint64               `protobuf:"varint,3,rep,packed,name=member_user_ids,json=memberUserIds,proto3" json:"member_user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupRequest) Reset() {
	*x = CreateGroupRequest{}
	mi := &file_proto_group_v1_group_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupRequest) ProtoMessage() {}

func (x *CreateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_v1_group_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_group_v1_group_proto_rawDescGZIP(), []int{2}
}

func (x *CreateGroupRequest) GetOwnerUserId() uint64 {
	if x != nil {
		return x.OwnerUserId
	}
	return 0
}

func (x *CreateGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGroupRequest) GetMemberUserIds() []uint64 {
	if x != nil {
		return x.MemberUserIds
	}
	return nil
}

// 创建group响应
type CreateGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *Group                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupResponse) Reset() {
	*x = CreateGroupResponse{}
	mi := &file_proto_group_v1_group_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupResponse) ProtoMessage() {}

func (x *CreateGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_v1_group_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupResponse.ProtoReflect.Descriptor instead.
func (*CreateGroupResponse) Descriptor() ([]byte, []int) {
	return file_proto_group_v1_group_proto_rawDescGZIP(), []int{3}
}

func (x *CreateGroupResponse) GetGroup() *Group {
	if x != nil {
		return x.Group
	}
	return nil
}

// 添加成员请求
type AddMemberRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	GroupId        uint64                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OperatorUserId uint64                 `protobuf:"varint,2,opt,name=operator_user_id,json=operatorUserId,proto3" json:"operator_user_id,omitempty"`
	TargetUserId   uint64                 `protobuf:"varint,3,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AddMemberRequest) Reset() {
	*x = AddMemberRequest{}
	mi := &file_proto_group_v1_group_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMemberRequest) ProtoMessage() {}

func (x *AddMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_v1_group_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMemberRequest.ProtoReflect.Descriptor instead.
func (*AddMemberRequest) Descriptor() ([]byte, []int) {
	return file_proto_group_v1_group_proto_rawDescGZIP(), []int{4}
}

func (x *AddMemberRequest) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *AddMemberRequest) GetOperatorUserId() uint64 {
	if x != nil {
		return x.OperatorUserId
	}
	return 0
}

func (x *AddMemberRequest) GetTargetUserId() uint64 {
	if x != nil {
		return x.TargetUserId
	}
	return 0
}

// 添加成员响应
type AddMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMemberResponse) Reset() {
	*x = AddMemberResponse{}
	mi := &file_proto_group_v1_group_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMemberResponse) ProtoMessage() {}

func (x *AddMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_v1_group_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMemberResponse.ProtoReflect.Descriptor instead.
func (*AddMemberResponse) Descriptor() ([]byte, []int) {
	return file_proto_group_v1_group_proto_rawDescGZIP(), []int{5}
}

func (x *AddMemberResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 删除成员请求
type RemoveMemberRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	GroupId        uint64                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OperatorUserId uint64                 `protobuf:"varint,2,opt,name=operator_user_id,json=operatorUserId,proto3" json:"operator_user_id,omitempty"`
	TargetUserId   uint64                 `protobuf:"varint,3,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RemoveMemberRequest) Reset() {
	*x = RemoveMemberRequest{}
	mi := &file_proto_group_v1_group_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMemberRequest) ProtoMessage() {}

func (x *RemoveMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_v1_group_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMemberRequest.ProtoReflect.Descriptor instead.
func (*RemoveMemberRequest) Descriptor() ([]byte, []int) {
	return file_proto_group_v1_group_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveMemberRequest) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *RemoveMemberRequest) GetOperatorUserId() uint64 {
	if x != nil {
		return x.OperatorUserId
	}
	return 0
}

func (x *RemoveMemberRequest) GetTargetUserId() uint64 {
	if x != nil {
		return x.TargetUserId
	}
	return 0
}

// 删除成员响应
type RemoveMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMemberResponse) Reset() {
	*x = RemoveMemberResponse{}
	mi := &file_proto_group_v1_group_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMemberResponse) ProtoMessage() {}

func (x *RemoveMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_v1_group_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMemberResponse.ProtoReflect.Descriptor instead.
func (*RemoveMemberResponse) Descriptor() ([]byte, []int) {
	return file_proto_group_v1_group_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveMemberResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 列出成员请求
type ListMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       uint64                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersRequest) Reset() {
	*x = ListMembersRequest{}
	mi := &file_proto_group_v1_group_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersRequest) ProtoMessage() {}

func (x *ListMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_v1_group_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersRequest.ProtoReflect.Descriptor instead.
func (*ListMembersRequest) Descriptor() ([]byte, []int) {
	return file_proto_group_v1_group_proto_rawDescGZIP(), []int{8}
}

func (x *ListMembersRequest) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

// 列出成员响应
type ListMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*GroupMember         `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersResponse) Reset() {
	*x = ListMembersResponse{}
	mi := &file_proto_group_v1_group_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersResponse) ProtoMessage() {}

func (x *ListMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_v1_group_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersResponse.ProtoReflect.Descriptor instead.
func (*ListMembersResponse) Descriptor() ([]byte, []int) {
	return file_proto_group_v1_group_proto_rawDescGZIP(), []int{9}
}

func (x *ListMembersResponse) GetMembers() []*GroupMember {
	if x != nil {
		return x.Members
	}
	return nil
}

// 是否为成员请求
type IsMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       uint64                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsMemberRequest) Reset() {
	*x = IsMemberRequest{}
	mi := &file_proto_group_v1_group_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsMemberRequest) ProtoMessage() {}

func (x *IsMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_v1_group_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsMemberRequest.ProtoReflect.Descriptor instead.
func (*IsMemberRequest) Descriptor() ([]byte, []int) {
	return file_proto_group_v1_group_proto_rawDescGZIP(), []int{10}
}

func (x *IsMemberRequest) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *IsMemberRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 是否为成员响应
type IsMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsMember      bool                   `protobuf:"varint,1,opt,name=is_member,json=isMember,proto3" json:"is_member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsMemberResponse) Reset() {
	*x = IsMemberResponse{}
	mi := &file_proto_group_v1_group_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsMemberResponse) ProtoMessage() {}

func (x *IsMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_v1_group_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsMemberResponse.ProtoReflect.Descriptor instead.
func (*IsMemberResponse) Descriptor() ([]byte, []int) {
	return file_proto_group_v1_group_proto_rawDescGZIP(), []int{11}
}

func (x *IsMemberResponse) GetIsMember() bool {
	if x != nil {
		return x.IsMember
	}
	return false
}

// 列出某个用户加入的群请求
type ListUserGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserGroupsRequest) Reset() {
	*x = ListUserGroupsRequest{}
	mi := &file_proto_group_v1_group_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserGroupsRequest) ProtoMessage() {}

func (x *ListUserGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_v1_group_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListUserGroupsRequest) Descriptor() ([]byte, []int) {
	return file_proto_group_v1_group_proto_rawDescGZIP(), []int{12}
}

func (x *ListUserGroupsRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 列出某个用户加入的群响应
type ListUserGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*Group               `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserGroupsResponse) Reset() {
	*x = ListUserGroupsResponse{}
	mi := &file_proto_group_v1_group_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserGroupsResponse) ProtoMessage() {}

func (x *ListUserGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_v1_group_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListUserGroupsResponse) Descriptor() ([]byte, []int) {
	return file_proto_group_v1_group_proto_rawDescGZIP(), []int{13}
}

func (x *ListUserGroupsResponse) GetGroups() []*Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

type GroupMessageItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupId       uint64                 `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	FromUserId    uint64                 `protobuf:"varint,3,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	MessageType   string                 `protobuf:"bytes,4,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"` // text/system
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Seq           uint64                 `protobuf:"varint,6,opt,name=seq,proto3" json:"seq,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMessageItem) Reset() {
	*x = GroupMessageItem{}
	mi := &file_proto_group_v1_group_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMessageItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMessageItem) ProtoMessage() {}

func (x *GroupMessageItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_v1_group_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMessageItem.ProtoReflect.Descriptor instead.
func (*GroupMessageItem) Descriptor() ([]byte, []int) {
	return file_proto_group_v1_group_proto_rawDescGZIP(), []int{14}
}

func (x *GroupMessageItem) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GroupMessageItem) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupMessageItem) GetFromUserId() uint64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *GroupMessageItem) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *GroupMessageItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GroupMessageItem) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *GroupMessageItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ListGroupMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       uint64                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	BeforeSeq     uint64                 `protobuf:"varint,4,opt,name=before_seq,json=beforeSeq,proto3" json:"before_seq,omitempty"` // 仅返回 seq < before_seq 的历史消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupMessagesRequest) Reset() {
	*x = ListGroupMessagesRequest{}
	mi := &file_proto_group_v1_group_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupMessagesRequest) ProtoMessage() {}

func (x *ListGroupMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_v1_group_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListGroupMessagesRequest) Descriptor() ([]byte, []int) {
	return file_proto_group_v1_group_proto_rawDescGZIP(), []int{15}
}

func (x *ListGroupMessagesRequest) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *ListGroupMessagesRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListGroupMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListGroupMessagesRequest) GetBeforeSeq() uint64 {
	if x != nil {
		return x.BeforeSeq
	}
	return 0
}

type ListGroupMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*GroupMessageItem    `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	NextBeforeSeq uint64                 `protobuf:"varint,3,opt,name=next_before_seq,json=nextBeforeSeq,proto3" json:"next_before_seq,omitempty"` // 下一次分页可传该值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupMessagesResponse) Reset() {
	*x = ListGroupMessagesResponse{}
	mi := &file_proto_group_v1_group_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupMessagesResponse) ProtoMessage() {}

func (x *ListGroupMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_v1_group_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupMessagesResponse.ProtoReflect.Descriptor instead.
func (*ListGroupMessagesResponse) Descriptor() ([]byte, []int) {
	return file_proto_group_v1_group_proto_rawDescGZIP(), []int{16}
}

func (x *ListGroupMessagesResponse) GetMessages() []*GroupMessageItem {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ListGroupMessagesResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *ListGroupMessagesResponse) GetNextBeforeSeq() uint64 {
	if x != nil {
		return x.NextBeforeSeq
	}
	return 0
}

type GetGroupRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	GroupId        uint64                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OperatorUserId uint64                 `protobuf:"varint,2,opt,name=operator_user_id,json=operatorUserId,proto3" json:"operator_user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetGroupRequest) Reset() {
	*x = GetGroupRequest{}
	mi := &file_proto_group_v1_group_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupRequest) ProtoMessage() {}

func (x *GetGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_v1_group_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupRequest.ProtoReflect.Descriptor instead.
func (*GetGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_group_v1_group_proto_rawDescGZIP(), []int{17}
}

func (x *GetGroupRequest) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GetGroupRequest) GetOperatorUserId() uint64 {
	if x != nil {
		return x.OperatorUserId
	}
	return 0
}

type GetGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *Group                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupResponse) Reset() {
	*x = GetGroupResponse{}
	mi := &file_proto_group_v1_group_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupResponse) ProtoMessage() {}

func (x *GetGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_v1_group_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupResponse.ProtoReflect.Descriptor instead.
func (*GetGroupResponse) Descriptor() ([]byte, []int) {
	return file_proto_group_v1_group_proto_rawDescGZIP(), []int{18}
}

func (x *GetGroupResponse) GetGroup() *Group {
	if x != nil {
		return x.Group
	}
	return nil
}

type UpdateGroupRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	GroupId        uint64                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OperatorUserId uint64                 `protobuf:"varint,2,opt,name=operator_user_id,json=operatorUserId,proto3" json:"operator_user_id,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Notice         string                 `protobuf:"bytes,4,opt,name=notice,proto3" json:"notice,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateGroupRequest) Reset() {
	*x = UpdateGroupRequest{}
	mi := &file_proto_group_v1_group_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupRequest) ProtoMessage() {}

func (x *UpdateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_v1_group_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupRequest.ProtoReflect.Descriptor instead.
func (*UpdateGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_group_v1_group_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateGroupRequest) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *UpdateGroupRequest) GetOperatorUserId() uint64 {
	if x != nil {
		return x.OperatorUserId
	}
	return 0
}

func (x *UpdateGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateGroupRequest) GetNotice() string {
	if x != nil {
		return x.Notice
	}
	return ""
}

type UpdateGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *Group                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupResponse) Reset() {
	*x = UpdateGroupResponse{}
	mi := &file_proto_group_v1_group_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupResponse) ProtoMessage() {}

func (x *UpdateGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_v1_group_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupResponse.ProtoReflect.Descriptor instead.
func (*UpdateGroupResponse) Descriptor() ([]byte, []int) {
	return file_proto_group_v1_group_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateGroupResponse) GetGroup() *Group {
	if x != nil {
		return x.Group
	}
	return nil
}

type LeaveGroupRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	GroupId        uint64                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OperatorUserId uint64                 `protobuf:"varint,2,opt,name=operator_user_id,json=operatorUserId,proto3" json:"operator_user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LeaveGroupRequest) Reset() {
	*x = LeaveGroupRequest{}
	mi := &file_proto_group_v1_group_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveGroupRequest) ProtoMessage() {}

func (x *LeaveGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_v1_group_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveGroupRequest.ProtoReflect.Descriptor instead.
func (*LeaveGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_group_v1_group_proto_rawDescGZIP(), []int{21}
}

func (x *LeaveGroupRequest) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *LeaveGroupRequest) GetOperatorUserId() uint64 {
	if x != nil {
		return x.OperatorUserId
	}
	return 0
}

type LeaveGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveGroupResponse) Reset() {
	*x = LeaveGroupResponse{}
	mi := &file_proto_group_v1_group_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveGroupResponse) ProtoMessage() {}

func (x *LeaveGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_v1_group_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveGroupResponse.ProtoReflect.Descriptor instead.
func (*LeaveGroupResponse) Descriptor() ([]byte, []int) {
	return file_proto_group_v1_group_proto_rawDescGZIP(), []int{22}
}

func (x *LeaveGroupResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DisbandGroupRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	GroupId        uint64                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OperatorUserId uint64                 `protobuf:"varint,2,opt,name=operator_user_id,json=operatorUserId,proto3" json:"operator_user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DisbandGroupRequest) Reset() {
	*x = DisbandGroupRequest{}
	mi := &file_proto_group_v1_group_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisbandGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisbandGroupRequest) ProtoMessage() {}

func (x *DisbandGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_v1_group_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisbandGroupRequest.ProtoReflect.Descriptor instead.
func (*DisbandGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_group_v1_group_proto_rawDescGZIP(), []int{23}
}

func (x *DisbandGroupRequest) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *DisbandGroupRequest) GetOperatorUserId() uint64 {
	if x != nil {
		return x.OperatorUserId
	}
	return 0
}

type DisbandGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisbandGroupResponse) Reset() {
	*x = DisbandGroupResponse{}
	mi := &file_proto_group_v1_group_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisbandGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisbandGroupResponse) ProtoMessage() {}

func (x *DisbandGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_v1_group_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisbandGroupResponse.ProtoReflect.Descriptor instead.
func (*DisbandGroupResponse) Descriptor() ([]byte, []int) {
	return file_proto_group_v1_group_proto_rawDescGZIP(), []int{24}
}

func (x *DisbandGroupResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TransferOwnerRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	GroupId        uint64                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OperatorUserId uint64                 `protobuf:"varint,2,opt,name=operator_user_id,json=operatorUserId,proto3" json:"operator_user_id,omitempty"`
	TargetUserId   uint64                 `protobuf:"varint,3,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TransferOwnerRequest) Reset() {
	*x = TransferOwnerRequest{}
	mi := &file_proto_group_v1_group_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferOwnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferOwnerRequest) ProtoMessage() {}

func (x *TransferOwnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_v1_group_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferOwnerRequest.ProtoReflect.Descriptor instead.
func (*TransferOwnerRequest) Descriptor() ([]byte, []int) {
	return file_proto_group_v1_group_proto_rawDescGZIP(), []int{25}
}

func (x *TransferOwnerRequest) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *TransferOwnerRequest) GetOperatorUserId() uint64 {
	if x != nil {
		return x.OperatorUserId
	}
	return 0
}

func (x *TransferOwnerRequest) GetTargetUserId() uint64 {
	if x != nil {
		return x.TargetUserId
	}
	return 0
}

type TransferOwnerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *Group                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferOwnerResponse) Reset() {
	*x = TransferOwnerResponse{}
	mi := &file_proto_group_v1_group_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferOwnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferOwnerResponse) ProtoMessage() {}

func (x *TransferOwnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_v1_group_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferOwnerResponse.ProtoReflect.Descriptor instead.
func (*TransferOwnerResponse) Descriptor() ([]byte, []int) {
	return file_proto_group_v1_group_proto_rawDescGZIP(), []int{26}
}

func (x *TransferOwnerResponse) GetGroup() *Group {
	if x != nil {
		return x.Group
	}
	return nil
}

type AppendSystemMessageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	GroupId        uint64                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OperatorUserId uint64                 `protobuf:"varint,2,opt,name=operator_user_id,json=operatorUserId,proto3" json:"operator_user_id,omitempty"`
	EventType      string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Content        string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	EventId        string                 `protobuf:"bytes,5,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AppendSystemMessageRequest) Reset() {
	*x = AppendSystemMessageRequest{}
	mi := &file_proto_group_v1_group_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendSystemMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendSystemMessageRequest) ProtoMessage() {}

func (x *AppendSystemMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_v1_group_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendSystemMessageRequest.ProtoReflect.Descriptor instead.
func (*AppendSystemMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_group_v1_group_proto_rawDescGZIP(), []int{27}
}

func (x *AppendSystemMessageRequest) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *AppendSystemMessageRequest) GetOperatorUserId() uint64 {
	if x != nil {
		return x.OperatorUserId
	}
	return 0
}

func (x *AppendSystemMessageRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *AppendSystemMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AppendSystemMessageRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type AppendSystemMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendSystemMessageResponse) Reset() {
	*x = AppendSystemMessageResponse{}
	mi := &file_proto_group_v1_group_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendSystemMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendSystemMessageResponse) ProtoMessage() {}

func (x *AppendSystemMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_v1_group_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendSystemMessageResponse.ProtoReflect.Descriptor instead.
func (*AppendSystemMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_group_v1_group_proto_rawDescGZIP(), []int{28}
}

func (x *AppendSystemMessageResponse) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type MarkGroupReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       uint64                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ReadSeq       uint64                 `protobuf:"varint,3,opt,name=read_seq,json=readSeq,proto3" json:"read_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkGroupReadRequest) Reset() {
	*x = MarkGroupReadRequest{}
	mi := &file_proto_group_v1_group_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkGroupReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkGroupReadRequest) ProtoMessage() {}

func (x *MarkGroupReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_v1_group_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkGroupReadRequest.ProtoReflect.Descriptor instead.
func (*MarkGroupReadRequest) Descriptor() ([]byte, []int) {
	return file_proto_group_v1_group_proto_rawDescGZIP(), []int{29}
}

func (x *MarkGroupReadRequest) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *MarkGroupReadRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MarkGroupReadRequest) GetReadSeq() uint64 {
	if x != nil {
		return x.ReadSeq
	}
	return 0
}

type MarkGroupReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReadSeq       uint64                 `protobuf:"varint,1,opt,name=read_seq,json=readSeq,proto3" json:"read_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkGroupReadResponse) Reset() {
	*x = MarkGroupReadResponse{}
	mi := &file_proto_group_v1_group_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkGroupReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkGroupReadResponse) ProtoMessage() {}

func (x *MarkGroupReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_v1_group_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkGroupReadResponse.ProtoReflect.Descriptor instead.
func (*MarkGroupReadResponse) Descriptor() ([]byte, []int) {
	return file_proto_group_v1_group_proto_rawDescGZIP(), []int{30}
}

func (x *MarkGroupReadResponse) GetReadSeq() uint64 {
	if x != nil {
		return x.ReadSeq
	}
	return 0
}

type GroupConversationItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *Group                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	LastSeq       uint64                 `protobuf:"varint,2,opt,name=last_seq,json=lastSeq,proto3" json:"last_seq,omitempty"`
	ReadSeq       uint64                 `protobuf:"varint,3,opt,name=read_seq,json=readSeq,proto3" json:"read_seq,omitempty"`
	UnreadCount   uint64                 `protobuf:"varint,4,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupConversationItem) Reset() {
	*x = GroupConversationItem{}
	mi := &file_proto_group_v1_group_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupConversationItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupConversationItem) ProtoMessage() {}

func (x *GroupConversationItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_v1_group_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupConversationItem.ProtoReflect.Descriptor instead.
func (*GroupConversationItem) Descriptor() ([]byte, []int) {
	return file_proto_group_v1_group_proto_rawDescGZIP(), []int{31}
}

func (x *GroupConversationItem) GetGroup() *Group {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *GroupConversationItem) GetLastSeq() uint64 {
	if x != nil {
		return x.LastSeq
	}
	return 0
}

func (x *GroupConversationItem) GetReadSeq() uint64 {
	if x != nil {
		return x.ReadSeq
	}
	return 0
}

func (x *GroupConversationItem) GetUnreadCount() uint64 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

type ListUserGroupConversationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserGroupConversationsRequest) Reset() {
	*x = ListUserGroupConversationsRequest{}
	mi := &file_proto_group_v1_group_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserGroupConversationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserGroupConversationsRequest) ProtoMessage() {}

func (x *ListUserGroupConversationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_v1_group_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserGroupConversationsRequest.ProtoReflect.Descriptor instead.
func (*ListUserGroupConversationsRequest) Descriptor() ([]byte, []int) {
	return file_proto_group_v1_group_proto_rawDescGZIP(), []int{32}
}

func (x *ListUserGroupConversationsRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListUserGroupConversationsResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Items         []*GroupConversationItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserGroupConversationsResponse) Reset() {
	*x = ListUserGroupConversationsResponse{}
	mi := &file_proto_group_v1_group_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserGroupConversationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserGroupConversationsResponse) ProtoMessage() {}

func (x *ListUserGroupConversationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_v1_group_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserGroupConversationsResponse.ProtoReflect.Descriptor instead.
func (*ListUserGroupConversationsResponse) Descriptor() ([]byte, []int) {
	return file_proto_group_v1_group_proto_rawDescGZIP(), []int{33}
}

func (x *ListUserGroupConversationsResponse) GetItems() []*GroupConversationItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_proto_group_v1_group_proto protoreflect.FileDescriptor

const file_proto_group_v1_group_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/group/v1/group.proto\x12\bgroup.v1\"\xa5\x01\n" +
	"\x05Group\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\"\n" +
	"\rowner_user_id\x18\x03 \x01(\x04R\vownerUserId\x12\x16\n" +
	"\x06notice\x18\x04 \x01(\tR\x06notice\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt\"\x82\x01\n" +
	"\vGroupMember\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x04R\agroupId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x04R\x06userId\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x1b\n" +
	"\tjoined_at\x18\x05 \x01(\x03R\bjoinedAt\"t\n" +
	"\x12CreateGroupRequest\x12\"\n" +
	"\rowner_user_id\x18\x01 \x01(\x04R\vownerUserId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12&\n" +
	"\x0fmember_user_ids\x18\x03 \x03(\x04R\rmemberUserIds\"<\n" +
	"\x13CreateGroupResponse\x12%\n" +
	"\x05group\x18\x01 \x01(\v2\x0f.group.v1.GroupR\x05group\"}\n" +
	"\x10AddMemberRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x04R\agroupId\x12(\n" +
	"\x10operator_user_id\x18\x02 \x01(\x04R\x0eoperatorUserId\x12$\n" +
	"\x0etarget_user_id\x18\x03 \x01(\x04R\ftargetUserId\"-\n" +
	"\x11AddMemberResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x80\x01\n" +
	"\x13RemoveMemberRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x04R\agroupId\x12(\n" +
	"\x10operator_user_id\x18\x02 \x01(\x04R\x0eoperatorUserId\x12$\n" +
	"\x0etarget_user_id\x18\x03 \x01(\x04R\ftargetUserId\"0\n" +
	"\x14RemoveMemberResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"/\n" +
	"\x12ListMembersRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x04R\agroupId\"F\n" +
	"\x13ListMembersResponse\x12/\n" +
	"\amembers\x18\x01 \x03(\v2\x15.group.v1.GroupMemberR\amembers\"E\n" +
	"\x0fIsMemberRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x04R\agroupId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\"/\n" +
	"\x10IsMemberResponse\x12\x1b\n" +
	"\tis_member\x18\x01 \x01(\bR\bisMember\"0\n" +
	"\x15ListUserGroupsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"A\n" +
	"\x16ListUserGroupsResponse\x12'\n" +
	"\x06groups\x18\x01 \x03(\v2\x0f.group.v1.GroupR\x06groups\"\xcd\x01\n" +
	"\x10GroupMessageItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x04R\agroupId\x12 \n" +
	"\ffrom_user_id\x18\x03 \x01(\x04R\n" +
	"fromUserId\x12!\n" +
	"\fmessage_type\x18\x04 \x01(\tR\vmessageType\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x10\n" +
	"\x03seq\x18\x06 \x01(\x04R\x03seq\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\"\x83\x01\n" +
	"\x18ListGroupMessagesRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x04R\agroupId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x1d\n" +
	"\n" +
	"before_seq\x18\x04 \x01(\x04R\tbeforeSeq\"\x96\x01\n" +
	"\x19ListGroupMessagesResponse\x126\n" +
	"\bmessages\x18\x01 \x03(\v2\x1a.group.v1.GroupMessageItemR\bmessages\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\x12&\n" +
	"\x0fnext_before_seq\x18\x03 \x01(\x04R\rnextBeforeSeq\"V\n" +
	"\x0fGetGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x04R\agroupId\x12(\n" +
	"\x10operator_user_id\x18\x02 \x01(\x04R\x0eoperatorUserId\"9\n" +
	"\x10GetGroupResponse\x12%\n" +
	"\x05group\x18\x01 \x01(\v2\x0f.group.v1.GroupR\x05group\"\x85\x01\n" +
	"\x12UpdateGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x04R\agroupId\x12(\n" +
	"\x10operator_user_id\x18\x02 \x01(\x04R\x0eoperatorUserId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06notice\x18\x04 \x01(\tR\x06notice\"<\n" +
	"\x13UpdateGroupResponse\x12%\n" +
	"\x05group\x18\x01 \x01(\v2\x0f.group.v1.GroupR\x05group\"X\n" +
	"\x11LeaveGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x04R\agroupId\x12(\n" +
	"\x10operator_user_id\x18\x02 \x01(\x04R\x0eoperatorUserId\".\n" +
	"\x12LeaveGroupResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"Z\n" +
	"\x13DisbandGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x04R\agroupId\x12(\n" +
	"\x10operator_user_id\x18\x02 \x01(\x04R\x0eoperatorUserId\"0\n" +
	"\x14DisbandGroupResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x81\x01\n" +
	"\x14TransferOwnerRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x04R\agroupId\x12(\n" +
	"\x10operator_user_id\x18\x02 \x01(\x04R\x0eoperatorUserId\x12$\n" +
	"\x0etarget_user_id\x18\x03 \x01(\x04R\ftargetUserId\">\n" +
	"\x15TransferOwnerResponse\x12%\n" +
	"\x05group\x18\x01 \x01(\v2\x0f.group.v1.GroupR\x05group\"\xb5\x01\n" +
	"\x1aAppendSystemMessageRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x04R\agroupId\x12(\n" +
	"\x10operator_user_id\x18\x02 \x01(\x04R\x0eoperatorUserId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x19\n" +
	"\bevent_id\x18\x05 \x01(\tR\aeventId\"/\n" +
	"\x1bAppendSystemMessageResponse\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\"e\n" +
	"\x14MarkGroupReadRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x04R\agroupId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x19\n" +
	"\bread_seq\x18\x03 \x01(\x04R\areadSeq\"2\n" +
	"\x15MarkGroupReadResponse\x12\x19\n" +
	"\bread_seq\x18\x01 \x01(\x04R\areadSeq\"\x97\x01\n" +
	"\x15GroupConversationItem\x12%\n" +
	"\x05group\x18\x01 \x01(\v2\x0f.group.v1.GroupR\x05group\x12\x19\n" +
	"\blast_seq\x18\x02 \x01(\x04R\alastSeq\x12\x19\n" +
	"\bread_seq\x18\x03 \x01(\x04R\areadSeq\x12!\n" +
	"\funread_count\x18\x04 \x01(\x04R\vunreadCount\"<\n" +
	"!ListUserGroupConversationsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"[\n" +
	"\"ListUserGroupConversationsResponse\x125\n" +
	"\x05items\x18\x01 \x03(\v2\x1f.group.v1.GroupConversationItemR\x05items2\xd9\t\n" +
	"\fGroupService\x12J\n" +
	"\vCreateGroup\x12\x1c.group.v1.CreateGroupRequest\x1a\x1d.group.v1.CreateGroupResponse\x12D\n" +
	"\tAddMember\x12\x1a.group.v1.AddMemberRequest\x1a\x1b.group.v1.AddMemberResponse\x12M\n" +
	"\fRemoveMember\x12\x1d.group.v1.RemoveMemberRequest\x1a\x1e.group.v1.RemoveMemberResponse\x12J\n" +
	"\vListMembers\x12\x1c.group.v1.ListMembersRequest\x1a\x1d.group.v1.ListMembersResponse\x12A\n" +
	"\bIsMember\x12\x19.group.v1.IsMemberRequest\x1a\x1a.group.v1.IsMemberResponse\x12S\n" +
	"\x0eListUserGroups\x12\x1f.group.v1.ListUserGroupsRequest\x1a .group.v1.ListUserGroupsResponse\x12\\\n" +
	"\x11ListGroupMessages\x12\".group.v1.ListGroupMessagesRequest\x1a#.group.v1.ListGroupMessagesResponse\x12A\n" +
	"\bGetGroup\x12\x19.group.v1.GetGroupRequest\x1a\x1a.group.v1.GetGroupResponse\x12J\n" +
	"\vUpdateGroup\x12\x1c.group.v1.UpdateGroupRequest\x1a\x1d.group.v1.UpdateGroupResponse\x12G\n" +
	"\n" +
	"LeaveGroup\x12\x1b.group.v1.LeaveGroupRequest\x1a\x1c.group.v1.LeaveGroupResponse\x12M\n" +
	"\fDisbandGroup\x12\x1d.group.v1.DisbandGroupRequest\x1a\x1e.group.v1.DisbandGroupResponse\x12P\n" +
	"\rTransferOwner\x12\x1e.group.v1.TransferOwnerRequest\x1a\x1f.group.v1.TransferOwnerResponse\x12b\n" +
	"\x13AppendSystemMessage\x12$.group.v1.AppendSystemMessageRequest\x1a%.group.v1.AppendSystemMessageResponse\x12P\n" +
	"\rMarkGroupRead\x12\x1e.group.v1.MarkGroupReadRequest\x1a\x1f.group.v1.MarkGroupReadResponse\x12w\n" +
	"\x1aListUserGroupConversations\x12+.group.v1.ListUserGroupConversationsRequest\x1a,.group.v1.ListUserGroupConversationsResponseB\x1fZ\x1dpim/internal/group/pb;pbgroupb\x06proto3"

var (
	file_proto_group_v1_group_proto_rawDescOnce sync.Once
	file_proto_group_v1_group_proto_rawDescData []byte
)

func file_proto_group_v1_group_proto_rawDescGZIP() []byte {
	file_proto_group_v1_group_proto_rawDescOnce.Do(func() {
		file_proto_group_v1_group_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_group_v1_group_proto_rawDesc), len(file_proto_group_v1_group_proto_rawDesc)))
	})
	return file_proto_group_v1_group_proto_rawDescData
}

var file_proto_group_v1_group_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_proto_group_v1_group_proto_goTypes = []any{
	(*Group)(nil),                              // 0: group.v1.Group
	(*GroupMember)(nil),                        // 1: group.v1.GroupMember
	(*CreateGroupRequest)(nil),                 // 2: group.v1.CreateGroupRequest
	(*CreateGroupResponse)(nil),                // 3: group.v1.CreateGroupResponse
	(*AddMemberRequest)(nil),                   // 4: group.v1.AddMemberRequest
	(*AddMemberResponse)(nil),                  // 5: group.v1.AddMemberResponse
	(*RemoveMemberRequest)(nil),                // 6: group.v1.RemoveMemberRequest
	(*RemoveMemberResponse)(nil),               // 7: group.v1.RemoveMemberResponse
	(*ListMembersRequest)(nil),                 // 8: group.v1.ListMembersRequest
	(*ListMembersResponse)(nil),                // 9: group.v1.ListMembersResponse
	(*IsMemberRequest)(nil),                    // 10: group.v1.IsMemberRequest
	(*IsMemberResponse)(nil),                   // 11: group.v1.IsMemberResponse
	(*ListUserGroupsRequest)(nil),              // 12: group.v1.ListUserGroupsRequest
	(*ListUserGroupsResponse)(nil),             // 13: group.v1.ListUserGroupsResponse
	(*GroupMessageItem)(nil),                   // 14: group.v1.GroupMessageItem
	(*ListGroupMessagesRequest)(nil),           // 15: group.v1.ListGroupMessagesRequest
	(*ListGroupMessagesResponse)(nil),          // 16: group.v1.ListGroupMessagesResponse
	(*GetGroupRequest)(nil),                    // 17: group.v1.GetGroupRequest
	(*GetGroupResponse)(nil),                   // 18: group.v1.GetGroupResponse
	(*UpdateGroupRequest)(nil),                 // 19: group.v1.UpdateGroupRequest
	(*UpdateGroupResponse)(nil),                // 20: group.v1.UpdateGroupResponse
	(*LeaveGroupRequest)(nil),                  // 21: group.v1.LeaveGroupRequest
	(*LeaveGroupResponse)(nil),                 // 22: group.v1.LeaveGroupResponse
	(*DisbandGroupRequest)(nil),                // 23: group.v1.DisbandGroupRequest
	(*DisbandGroupResponse)(nil),               // 24: group.v1.DisbandGroupResponse
	(*TransferOwnerRequest)(nil),               // 25: group.v1.TransferOwnerRequest
	(*TransferOwnerResponse)(nil),              // 26: group.v1.TransferOwnerResponse
	(*AppendSystemMessageRequest)(nil),         // 27: group.v1.AppendSystemMessageRequest
	(*AppendSystemMessageResponse)(nil),        // 28: group.v1.AppendSystemMessageResponse
	(*MarkGroupReadRequest)(nil),               // 29: group.v1.MarkGroupReadRequest
	(*MarkGroupReadResponse)(nil),              // 30: group.v1.MarkGroupReadResponse
	(*GroupConversationItem)(nil),              // 31: group.v1.GroupConversationItem
	(*ListUserGroupConversationsRequest)(nil),  // 32: group.v1.ListUserGroupConversationsRequest
	(*ListUserGroupConversationsResponse)(nil), // 33: group.v1.ListUserGroupConversationsResponse
}
var file_proto_group_v1_group_proto_depIdxs = []int32{
	0,  // 0: group.v1.CreateGroupResponse.group:type_name -> group.v1.Group
	1,  // 1: group.v1.ListMembersResponse.members:type_name -> group.v1.GroupMember
	0,  // 2: group.v1.ListUserGroupsResponse.groups:type_name -> group.v1.Group
	14, // 3: group.v1.ListGroupMessagesResponse.messages:type_name -> group.v1.GroupMessageItem
	0,  // 4: group.v1.GetGroupResponse.group:type_name -> group.v1.Group
	0,  // 5: group.v1.UpdateGroupResponse.group:type_name -> group.v1.Group
	0,  // 6: group.v1.TransferOwnerResponse.group:type_name -> group.v1.Group
	0,  // 7: group.v1.GroupConversationItem.group:type_name -> group.v1.Group
	31, // 8: group.v1.ListUserGroupConversationsResponse.items:type_name -> group.v1.GroupConversationItem
	2,  // 9: group.v1.GroupService.CreateGroup:input_type -> group.v1.CreateGroupRequest
	4,  // 10: group.v1.GroupService.AddMember:input_type -> group.v1.AddMemberRequest
	6,  // 11: group.v1.GroupService.RemoveMember:input_type -> group.v1.RemoveMemberRequest
	8,  // 12: group.v1.GroupService.ListMembers:input_type -> group.v1.ListMembersRequest
	10, // 13: group.v1.GroupService.IsMember:input_type -> group.v1.IsMemberRequest
	12, // 14: group.v1.GroupService.ListUserGroups:input_type -> group.v1.ListUserGroupsRequest
	15, // 15: group.v1.GroupService.ListGroupMessages:input_type -> group.v1.ListGroupMessagesRequest
	17, // 16: group.v1.GroupService.GetGroup:input_type -> group.v1.GetGroupRequest
	19, // 17: group.v1.GroupService.UpdateGroup:input_type -> group.v1.UpdateGroupRequest
	21, // 18: group.v1.GroupService.LeaveGroup:input_type -> group.v1.LeaveGroupRequest
	23, // 19: group.v1.GroupService.DisbandGroup:input_type -> group.v1.DisbandGroupRequest
	25, // 20: group.v1.GroupService.TransferOwner:input_type -> group.v1.TransferOwnerRequest
	27, // 21: group.v1.GroupService.AppendSystemMessage:input_type -> group.v1.AppendSystemMessageRequest
	29, // 22: group.v1.GroupService.MarkGroupRead:input_type -> group.v1.MarkGroupReadRequest
	32, // 23: group.v1.GroupService.ListUserGroupConversations:input_type -> group.v1.ListUserGroupConversationsRequest
	3,  // 24: group.v1.GroupService.CreateGroup:output_type -> group.v1.CreateGroupResponse
	5,  // 25: group.v1.GroupService.AddMember:output_type -> group.v1.AddMemberResponse
	7,  // 26: group.v1.GroupService.RemoveMember:output_type -> group.v1.RemoveMemberResponse
	9,  // 27: group.v1.GroupService.ListMembers:output_type -> group.v1.ListMembersResponse
	11, // 28: group.v1.GroupService.IsMember:output_type -> group.v1.IsMemberResponse
	13, // 29: group.v1.GroupService.ListUserGroups:output_type -> group.v1.ListUserGroupsResponse
	16, // 30: group.v1.GroupService.ListGroupMessages:output_type -> group.v1.ListGroupMessagesResponse
	18, // 31: group.v1.GroupService.GetGroup:output_type -> group.v1.GetGroupResponse
	20, // 32: group.v1.GroupService.UpdateGroup:output_type -> group.v1.UpdateGroupResponse
	22, // 33: group.v1.GroupService.LeaveGroup:output_type -> group.v1.LeaveGroupResponse
	24, // 34: group.v1.GroupService.DisbandGroup:output_type -> group.v1.DisbandGroupResponse
	26, // 35: group.v1.GroupService.TransferOwner:output_type -> group.v1.TransferOwnerResponse
	28, // 36: group.v1.GroupService.AppendSystemMessage:output_type -> group.v1.AppendSystemMessageResponse
	30, // 37: group.v1.GroupService.MarkGroupRead:output_type -> group.v1.MarkGroupReadResponse
	33, // 38: group.v1.GroupService.ListUserGroupConversations:output_type -> group.v1.ListUserGroupConversationsResponse
	24, // [24:39] is the sub-list for method output_type
	9,  // [9:24] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_group_v1_group_proto_init() }
func file_proto_group_v1_group_proto_init() {
	if File_proto_group_v1_group_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_group_v1_group_proto_rawDesc), len(file_proto_group_v1_group_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_group_v1_group_proto_goTypes,
		DependencyIndexes: file_proto_group_v1_group_proto_depIdxs,
		MessageInfos:      file_proto_group_v1_group_proto_msgTypes,
	}.Build()
	File_proto_group_v1_group_proto = out.File
	file_proto_group_v1_group_proto_goTypes = nil
	file_proto_group_v1_group_proto_depIdxs = nil
}
