// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: proto/conversation/v1/im_event.proto

package pbconversation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IMKafkaMessage 用于 im-message / im-message-push 主题的内部事件载荷。
type IMKafkaMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	FromUserId    uint64                 `protobuf:"varint,2,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	ToUserId      uint64                 `protobuf:"varint,3,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	ClientMsgId   string                 `protobuf:"bytes,5,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IMKafkaMessage) Reset() {
	*x = IMKafkaMessage{}
	mi := &file_proto_conversation_v1_im_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IMKafkaMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IMKafkaMessage) ProtoMessage() {}

func (x *IMKafkaMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_conversation_v1_im_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IMKafkaMessage.ProtoReflect.Descriptor instead.
func (*IMKafkaMessage) Descriptor() ([]byte, []int) {
	return file_proto_conversation_v1_im_event_proto_rawDescGZIP(), []int{0}
}

func (x *IMKafkaMessage) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *IMKafkaMessage) GetFromUserId() uint64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *IMKafkaMessage) GetToUserId() uint64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

func (x *IMKafkaMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *IMKafkaMessage) GetClientMsgId() string {
	if x != nil {
		return x.ClientMsgId
	}
	return ""
}

var File_proto_conversation_v1_im_event_proto protoreflect.FileDescriptor

const file_proto_conversation_v1_im_event_proto_rawDesc = "" +
	"\n" +
	"$proto/conversation/v1/im_event.proto\x12\x0fconversation.v1\"\xa9\x01\n" +
	"\x0eIMKafkaMessage\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12 \n" +
	"\ffrom_user_id\x18\x02 \x01(\x04R\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x03 \x01(\x04R\btoUserId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\"\n" +
	"\rclient_msg_id\x18\x05 \x01(\tR\vclientMsgIdB-Z+pim/internal/conversation/pb;pbconversationb\x06proto3"

var (
	file_proto_conversation_v1_im_event_proto_rawDescOnce sync.Once
	file_proto_conversation_v1_im_event_proto_rawDescData []byte
)

func file_proto_conversation_v1_im_event_proto_rawDescGZIP() []byte {
	file_proto_conversation_v1_im_event_proto_rawDescOnce.Do(func() {
		file_proto_conversation_v1_im_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_conversation_v1_im_event_proto_rawDesc), len(file_proto_conversation_v1_im_event_proto_rawDesc)))
	})
	return file_proto_conversation_v1_im_event_proto_rawDescData
}

var file_proto_conversation_v1_im_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_conversation_v1_im_event_proto_goTypes = []any{
	(*IMKafkaMessage)(nil), // 0: conversation.v1.IMKafkaMessage
}
var file_proto_conversation_v1_im_event_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_conversation_v1_im_event_proto_init() }
func file_proto_conversation_v1_im_event_proto_init() {
	if File_proto_conversation_v1_im_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_conversation_v1_im_event_proto_rawDesc), len(file_proto_conversation_v1_im_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_conversation_v1_im_event_proto_goTypes,
		DependencyIndexes: file_proto_conversation_v1_im_event_proto_depIdxs,
		MessageInfos:      file_proto_conversation_v1_im_event_proto_msgTypes,
	}.Build()
	File_proto_conversation_v1_im_event_proto = out.File
	file_proto_conversation_v1_im_event_proto_goTypes = nil
	file_proto_conversation_v1_im_event_proto_depIdxs = nil
}
