// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: proto/group/v1/group_event.proto

package pbgroup

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GroupKafkaMessage 用于 group-message 主题的内部事件载荷。
type GroupKafkaMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	GroupId       uint64                 `protobuf:"varint,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	FromUserId    uint64                 `protobuf:"varint,4,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupKafkaMessage) Reset() {
	*x = GroupKafkaMessage{}
	mi := &file_proto_group_v1_group_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupKafkaMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupKafkaMessage) ProtoMessage() {}

func (x *GroupKafkaMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_v1_group_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupKafkaMessage.ProtoReflect.Descriptor instead.
func (*GroupKafkaMessage) Descriptor() ([]byte, []int) {
	return file_proto_group_v1_group_event_proto_rawDescGZIP(), []int{0}
}

func (x *GroupKafkaMessage) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *GroupKafkaMessage) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *GroupKafkaMessage) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupKafkaMessage) GetFromUserId() uint64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *GroupKafkaMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_proto_group_v1_group_event_proto protoreflect.FileDescriptor

const file_proto_group_v1_group_event_proto_rawDesc = "" +
	"\n" +
	" proto/group/v1/group_event.proto\x12\bgroup.v1\"\xa0\x01\n" +
	"\x11GroupKafkaMessage\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x19\n" +
	"\bgroup_id\x18\x03 \x01(\x04R\agroupId\x12 \n" +
	"\ffrom_user_id\x18\x04 \x01(\x04R\n" +
	"fromUserId\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontentB\x1fZ\x1dpim/internal/group/pb;pbgroupb\x06proto3"

var (
	file_proto_group_v1_group_event_proto_rawDescOnce sync.Once
	file_proto_group_v1_group_event_proto_rawDescData []byte
)

func file_proto_group_v1_group_event_proto_rawDescGZIP() []byte {
	file_proto_group_v1_group_event_proto_rawDescOnce.Do(func() {
		file_proto_group_v1_group_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_group_v1_group_event_proto_rawDesc), len(file_proto_group_v1_group_event_proto_rawDesc)))
	})
	return file_proto_group_v1_group_event_proto_rawDescData
}

var file_proto_group_v1_group_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_group_v1_group_event_proto_goTypes = []any{
	(*GroupKafkaMessage)(nil), // 0: group.v1.GroupKafkaMessage
}
var file_proto_group_v1_group_event_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_group_v1_group_event_proto_init() }
func file_proto_group_v1_group_event_proto_init() {
	if File_proto_group_v1_group_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_group_v1_group_event_proto_rawDesc), len(file_proto_group_v1_group_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_group_v1_group_event_proto_goTypes,
		DependencyIndexes: file_proto_group_v1_group_event_proto_depIdxs,
		MessageInfos:      file_proto_group_v1_group_event_proto_msgTypes,
	}.Build()
	File_proto_group_v1_group_event_proto = out.File
	file_proto_group_v1_group_event_proto_goTypes = nil
	file_proto_group_v1_group_event_proto_depIdxs = nil
}
