// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: proto/group/v1/group_push.proto

package pbgroup

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GroupPushMessage 为 group-service -> gateway PushService 的内部下行载荷。
type GroupPushMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // group_message
	GroupId       uint64                 `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	FromUserId    uint64                 `protobuf:"varint,3,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	MessageType   string                 `protobuf:"bytes,4,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Seq           uint64                 `protobuf:"varint,6,opt,name=seq,proto3" json:"seq,omitempty"`
	MentionMeta   string                 `protobuf:"bytes,7,opt,name=mention_meta,json=mentionMeta,proto3" json:"mention_meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupPushMessage) Reset() {
	*x = GroupPushMessage{}
	mi := &file_proto_group_v1_group_push_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupPushMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupPushMessage) ProtoMessage() {}

func (x *GroupPushMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_v1_group_push_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupPushMessage.ProtoReflect.Descriptor instead.
func (*GroupPushMessage) Descriptor() ([]byte, []int) {
	return file_proto_group_v1_group_push_proto_rawDescGZIP(), []int{0}
}

func (x *GroupPushMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GroupPushMessage) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupPushMessage) GetFromUserId() uint64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *GroupPushMessage) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *GroupPushMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GroupPushMessage) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *GroupPushMessage) GetMentionMeta() string {
	if x != nil {
		return x.MentionMeta
	}
	return ""
}

var File_proto_group_v1_group_push_proto protoreflect.FileDescriptor

const file_proto_group_v1_group_push_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/group/v1/group_push.proto\x12\bgroup.v1\"\xd5\x01\n" +
	"\x10GroupPushMessage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x04R\agroupId\x12 \n" +
	"\ffrom_user_id\x18\x03 \x01(\x04R\n" +
	"fromUserId\x12!\n" +
	"\fmessage_type\x18\x04 \x01(\tR\vmessageType\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x10\n" +
	"\x03seq\x18\x06 \x01(\x04R\x03seq\x12!\n" +
	"\fmention_meta\x18\a \x01(\tR\vmentionMetaB\x1cZ\x1apim/proto/group/v1;pbgroupb\x06proto3"

var (
	file_proto_group_v1_group_push_proto_rawDescOnce sync.Once
	file_proto_group_v1_group_push_proto_rawDescData []byte
)

func file_proto_group_v1_group_push_proto_rawDescGZIP() []byte {
	file_proto_group_v1_group_push_proto_rawDescOnce.Do(func() {
		file_proto_group_v1_group_push_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_group_v1_group_push_proto_rawDesc), len(file_proto_group_v1_group_push_proto_rawDesc)))
	})
	return file_proto_group_v1_group_push_proto_rawDescData
}

var file_proto_group_v1_group_push_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_group_v1_group_push_proto_goTypes = []any{
	(*GroupPushMessage)(nil), // 0: group.v1.GroupPushMessage
}
var file_proto_group_v1_group_push_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_group_v1_group_push_proto_init() }
func file_proto_group_v1_group_push_proto_init() {
	if File_proto_group_v1_group_push_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_group_v1_group_push_proto_rawDesc), len(file_proto_group_v1_group_push_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_group_v1_group_push_proto_goTypes,
		DependencyIndexes: file_proto_group_v1_group_push_proto_depIdxs,
		MessageInfos:      file_proto_group_v1_group_push_proto_msgTypes,
	}.Build()
	File_proto_group_v1_group_push_proto = out.File
	file_proto_group_v1_group_push_proto_goTypes = nil
	file_proto_group_v1_group_push_proto_depIdxs = nil
}
