// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: proto/gateway/v1/gateway.proto

package pbgateway

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushToConnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromUserId    uint64                 `protobuf:"varint,1,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"` // 谁发送的
	ToUserId      uint64                 `protobuf:"varint,2,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`       // 推给谁
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                            // 文本内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushToConnRequest) Reset() {
	*x = PushToConnRequest{}
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushToConnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushToConnRequest) ProtoMessage() {}

func (x *PushToConnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushToConnRequest.ProtoReflect.Descriptor instead.
func (*PushToConnRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_v1_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *PushToConnRequest) GetFromUserId() uint64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *PushToConnRequest) GetToUserId() uint64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

func (x *PushToConnRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type PushToConnResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`      // 是否写入成功（包括“线上但写失败”等）
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // 失败原因，ok=false 时可读
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushToConnResponse) Reset() {
	*x = PushToConnResponse{}
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushToConnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushToConnResponse) ProtoMessage() {}

func (x *PushToConnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushToConnResponse.ProtoReflect.Descriptor instead.
func (*PushToConnResponse) Descriptor() ([]byte, []int) {
	return file_proto_gateway_v1_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *PushToConnResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *PushToConnResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_gateway_v1_gateway_proto protoreflect.FileDescriptor

const file_proto_gateway_v1_gateway_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/gateway/v1/gateway.proto\x12\n" +
	"gateway.v1\"m\n" +
	"\x11PushToConnRequest\x12 \n" +
	"\ffrom_user_id\x18\x01 \x01(\x04R\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x02 \x01(\x04R\btoUserId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\":\n" +
	"\x12PushToConnResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2Z\n" +
	"\vPushService\x12K\n" +
	"\n" +
	"PushToConn\x12\x1d.gateway.v1.PushToConnRequest\x1a\x1e.gateway.v1.PushToConnResponseB#Z!pim/internal/gateway/pb;pbgatewayb\x06proto3"

var (
	file_proto_gateway_v1_gateway_proto_rawDescOnce sync.Once
	file_proto_gateway_v1_gateway_proto_rawDescData []byte
)

func file_proto_gateway_v1_gateway_proto_rawDescGZIP() []byte {
	file_proto_gateway_v1_gateway_proto_rawDescOnce.Do(func() {
		file_proto_gateway_v1_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gateway_v1_gateway_proto_rawDesc), len(file_proto_gateway_v1_gateway_proto_rawDesc)))
	})
	return file_proto_gateway_v1_gateway_proto_rawDescData
}

var file_proto_gateway_v1_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_gateway_v1_gateway_proto_goTypes = []any{
	(*PushToConnRequest)(nil),  // 0: gateway.v1.PushToConnRequest
	(*PushToConnResponse)(nil), // 1: gateway.v1.PushToConnResponse
}
var file_proto_gateway_v1_gateway_proto_depIdxs = []int32{
	0, // 0: gateway.v1.PushService.PushToConn:input_type -> gateway.v1.PushToConnRequest
	1, // 1: gateway.v1.PushService.PushToConn:output_type -> gateway.v1.PushToConnResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_gateway_v1_gateway_proto_init() }
func file_proto_gateway_v1_gateway_proto_init() {
	if File_proto_gateway_v1_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gateway_v1_gateway_proto_rawDesc), len(file_proto_gateway_v1_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gateway_v1_gateway_proto_goTypes,
		DependencyIndexes: file_proto_gateway_v1_gateway_proto_depIdxs,
		MessageInfos:      file_proto_gateway_v1_gateway_proto_msgTypes,
	}.Build()
	File_proto_gateway_v1_gateway_proto = out.File
	file_proto_gateway_v1_gateway_proto_goTypes = nil
	file_proto_gateway_v1_gateway_proto_depIdxs = nil
}
