// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: proto/gateway/v1/gateway.proto

package pbgateway

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushToConnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromUserId    uint64                 `protobuf:"varint,1,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`    // 谁发送的
	ToUserId      uint64                 `protobuf:"varint,2,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`          // 推给谁
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                               // 文本内容
	ContentBytes  []byte                 `protobuf:"bytes,4,opt,name=content_bytes,json=contentBytes,proto3" json:"content_bytes,omitempty"` // 二进制内容（优先于 content）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushToConnRequest) Reset() {
	*x = PushToConnRequest{}
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushToConnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushToConnRequest) ProtoMessage() {}

func (x *PushToConnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushToConnRequest.ProtoReflect.Descriptor instead.
func (*PushToConnRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_v1_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *PushToConnRequest) GetFromUserId() uint64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *PushToConnRequest) GetToUserId() uint64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

func (x *PushToConnRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PushToConnRequest) GetContentBytes() []byte {
	if x != nil {
		return x.ContentBytes
	}
	return nil
}

type PushToConnResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`      // 是否写入成功（包括“线上但写失败”等）
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // 失败原因，ok=false 时可读
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushToConnResponse) Reset() {
	*x = PushToConnResponse{}
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushToConnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushToConnResponse) ProtoMessage() {}

func (x *PushToConnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushToConnResponse.ProtoReflect.Descriptor instead.
func (*PushToConnResponse) Descriptor() ([]byte, []int) {
	return file_proto_gateway_v1_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *PushToConnResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *PushToConnResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type PushBatchItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromUserId    uint64                 `protobuf:"varint,1,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	ToUserId      uint64                 `protobuf:"varint,2,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ContentBytes  []byte                 `protobuf:"bytes,4,opt,name=content_bytes,json=contentBytes,proto3" json:"content_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushBatchItem) Reset() {
	*x = PushBatchItem{}
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushBatchItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushBatchItem) ProtoMessage() {}

func (x *PushBatchItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushBatchItem.ProtoReflect.Descriptor instead.
func (*PushBatchItem) Descriptor() ([]byte, []int) {
	return file_proto_gateway_v1_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *PushBatchItem) GetFromUserId() uint64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *PushBatchItem) GetToUserId() uint64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

func (x *PushBatchItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PushBatchItem) GetContentBytes() []byte {
	if x != nil {
		return x.ContentBytes
	}
	return nil
}

type PushBatchToConnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*PushBatchItem       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushBatchToConnRequest) Reset() {
	*x = PushBatchToConnRequest{}
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushBatchToConnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushBatchToConnRequest) ProtoMessage() {}

func (x *PushBatchToConnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushBatchToConnRequest.ProtoReflect.Descriptor instead.
func (*PushBatchToConnRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_v1_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *PushBatchToConnRequest) GetItems() []*PushBatchItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type PushBatchToConnResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         uint32                 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Success       uint32                 `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Failed        uint32                 `protobuf:"varint,3,opt,name=failed,proto3" json:"failed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushBatchToConnResponse) Reset() {
	*x = PushBatchToConnResponse{}
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushBatchToConnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushBatchToConnResponse) ProtoMessage() {}

func (x *PushBatchToConnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_v1_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushBatchToConnResponse.ProtoReflect.Descriptor instead.
func (*PushBatchToConnResponse) Descriptor() ([]byte, []int) {
	return file_proto_gateway_v1_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *PushBatchToConnResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PushBatchToConnResponse) GetSuccess() uint32 {
	if x != nil {
		return x.Success
	}
	return 0
}

func (x *PushBatchToConnResponse) GetFailed() uint32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

var File_proto_gateway_v1_gateway_proto protoreflect.FileDescriptor

const file_proto_gateway_v1_gateway_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/gateway/v1/gateway.proto\x12\n" +
	"gateway.v1\"\x92\x01\n" +
	"\x11PushToConnRequest\x12 \n" +
	"\ffrom_user_id\x18\x01 \x01(\x04R\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x02 \x01(\x04R\btoUserId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12#\n" +
	"\rcontent_bytes\x18\x04 \x01(\fR\fcontentBytes\":\n" +
	"\x12PushToConnResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x8e\x01\n" +
	"\rPushBatchItem\x12 \n" +
	"\ffrom_user_id\x18\x01 \x01(\x04R\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x02 \x01(\x04R\btoUserId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12#\n" +
	"\rcontent_bytes\x18\x04 \x01(\fR\fcontentBytes\"I\n" +
	"\x16PushBatchToConnRequest\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.gateway.v1.PushBatchItemR\x05items\"a\n" +
	"\x17PushBatchToConnResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\rR\x05total\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\rR\asuccess\x12\x16\n" +
	"\x06failed\x18\x03 \x01(\rR\x06failed2\xb6\x01\n" +
	"\vPushService\x12K\n" +
	"\n" +
	"PushToConn\x12\x1d.gateway.v1.PushToConnRequest\x1a\x1e.gateway.v1.PushToConnResponse\x12Z\n" +
	"\x0fPushBatchToConn\x12\".gateway.v1.PushBatchToConnRequest\x1a#.gateway.v1.PushBatchToConnResponseB#Z!pim/internal/gateway/pb;pbgatewayb\x06proto3"

var (
	file_proto_gateway_v1_gateway_proto_rawDescOnce sync.Once
	file_proto_gateway_v1_gateway_proto_rawDescData []byte
)

func file_proto_gateway_v1_gateway_proto_rawDescGZIP() []byte {
	file_proto_gateway_v1_gateway_proto_rawDescOnce.Do(func() {
		file_proto_gateway_v1_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gateway_v1_gateway_proto_rawDesc), len(file_proto_gateway_v1_gateway_proto_rawDesc)))
	})
	return file_proto_gateway_v1_gateway_proto_rawDescData
}

var file_proto_gateway_v1_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_gateway_v1_gateway_proto_goTypes = []any{
	(*PushToConnRequest)(nil),       // 0: gateway.v1.PushToConnRequest
	(*PushToConnResponse)(nil),      // 1: gateway.v1.PushToConnResponse
	(*PushBatchItem)(nil),           // 2: gateway.v1.PushBatchItem
	(*PushBatchToConnRequest)(nil),  // 3: gateway.v1.PushBatchToConnRequest
	(*PushBatchToConnResponse)(nil), // 4: gateway.v1.PushBatchToConnResponse
}
var file_proto_gateway_v1_gateway_proto_depIdxs = []int32{
	2, // 0: gateway.v1.PushBatchToConnRequest.items:type_name -> gateway.v1.PushBatchItem
	0, // 1: gateway.v1.PushService.PushToConn:input_type -> gateway.v1.PushToConnRequest
	3, // 2: gateway.v1.PushService.PushBatchToConn:input_type -> gateway.v1.PushBatchToConnRequest
	1, // 3: gateway.v1.PushService.PushToConn:output_type -> gateway.v1.PushToConnResponse
	4, // 4: gateway.v1.PushService.PushBatchToConn:output_type -> gateway.v1.PushBatchToConnResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_gateway_v1_gateway_proto_init() }
func file_proto_gateway_v1_gateway_proto_init() {
	if File_proto_gateway_v1_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gateway_v1_gateway_proto_rawDesc), len(file_proto_gateway_v1_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gateway_v1_gateway_proto_goTypes,
		DependencyIndexes: file_proto_gateway_v1_gateway_proto_depIdxs,
		MessageInfos:      file_proto_gateway_v1_gateway_proto_msgTypes,
	}.Build()
	File_proto_gateway_v1_gateway_proto = out.File
	file_proto_gateway_v1_gateway_proto_goTypes = nil
	file_proto_gateway_v1_gateway_proto_depIdxs = nil
}
